using System;
using System.IO;
using sk0ya.Loomo.CSharp.Configuration;
using Editor.Core.Lsp;
using sk0ya.Loomo.CSharp.Projects;
using sk0ya.Loomo.CSharp.Refactoring;

namespace sk0ya.Loomo.Tests;

public sealed class CSharpCleanupServiceTests
{
    [Fact]
    public void Cleanup_options_factory_applies_the_file_editorconfig_snapshot()
    {
        var root = Path.Combine(Path.GetTempPath(),
            "LoomoCleanupOptions_" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        try
        {
            var path = Path.Combine(root, "Sample.cs");
            File.WriteAllText(path, "class Sample { }");
            File.WriteAllText(Path.Combine(root, ".editorconfig"),
                "root = true\n[*.cs]\nindent_style = tab\nindent_size = 2\n" +
                "tab_width = 2\ninsert_final_newline = false\n" +
                "dotnet_sort_system_directives_first = false\n");

            var options = CSharpCleanupOptionsFactory.CreateForFile(path, format: true);

            Assert.True(options.Format);
            Assert.Equal(2, options.IndentSize);
            Assert.Equal(2, options.TabWidth);
            Assert.True(options.UseTabs);
            Assert.False(options.InsertFinalNewline);
            Assert.False(options.SortSystemDirectivesFirst);
        }
        finally
        {
            if (Directory.Exists(root)) Directory.Delete(root, recursive: true);
        }
    }

    [Fact]
    public void Cleanup_combines_using_organization_and_safe_layout_cleanup()
    {
        const string source = "using Zed;\r\nusing System;\r\nusing System;\r\n\r\nclass Sample { \r\n    void Run() {\t\r\n    }\r\n}\r\n\r\n";

        var result = CSharpCleanupService.Clean(
            "C:\\work\\Sample.cs", source,
            new CSharpCleanupOptions(EndOfLine: "lf", InsertFinalNewline: true));

        Assert.Null(result.Error);
        Assert.False(result.IsGeneratedCode);
        Assert.NotNull(result.Edit);
        var edit = Assert.Single(Assert.Single(result.Edit!.Changes).Value);
        Assert.Equal("using System;\nusing Zed;\n\nclass Sample {\n    void Run() {\n    }\n}\n", edit.NewText);
        Assert.Contains("usingを整理", result.Summary);
        Assert.Contains("行変更", result.Summary);
    }

    [Fact]
    public void Semantic_cleanup_removes_only_compiler_reported_unused_usings()
    {
        const string path = "C:\\work\\Sample.cs";
        const string source = """
            using System;
            using System.Text;

            class Sample
            {
                void Run() => Console.WriteLine("ok");
            }
            """;
        var sources = new Dictionary<string, string> { [path] = source };
        var compilation = CSharpSemanticCompilation.Create(sources);

        var result = CSharpCleanupService.Clean(path, source,
            new CSharpCleanupOptions(
                Format: false,
                InsertFinalNewline: false,
                RemoveUnusedUsings: true),
            compilation);

        Assert.Null(result.Error);
        var updated = Assert.Single(Assert.Single(result.Edit!.Changes).Value).NewText;
        Assert.Contains("using System;", updated);
        Assert.DoesNotContain("using System.Text;", updated);
        Assert.Contains("Console.WriteLine", updated);
    }

    [Fact]
    public async Task Semantic_facade_organizes_usings_with_the_active_compilation()
    {
        const string path = "C:\\work\\Sample.cs";
        const string source = """
            using System;
            using System.Text;

            class Sample
            {
                void Run() => Console.WriteLine("ok");
            }
            """;

        var result = await CSharpSemanticOperations.OrganizeUsingsAsync(
            null, path, source);

        Assert.Null(result.Error);
        var updated = Assert.Single(Assert.Single(result.Edit!.Changes).Value).NewText;
        Assert.Contains("using System;", updated);
        Assert.DoesNotContain("using System.Text;", updated);
    }

    [Fact]
    public void Cleanup_excludes_generated_code_by_default_but_can_be_overridden()
    {
        const string source = "// <auto-generated />\nclass Generated {   \n}\n";

        var skipped = CSharpCleanupService.Clean("Generated.cs", source);
        Assert.True(skipped.IsGeneratedCode);
        Assert.Null(skipped.Edit);
        Assert.Contains("除外", skipped.Summary);

        var included = CSharpCleanupService.Clean(
            "Generated.cs", source,
            new CSharpCleanupOptions(OrganizeUsings: false, ExcludeGeneratedCode: false));
        Assert.False(included.IsGeneratedCode);
        Assert.NotNull(included.Edit);
        Assert.Equal("// <auto-generated />\nclass Generated {\n}\n", Assert.Single(Assert.Single(included.Edit!.Changes).Value).NewText);
    }

    [Fact]
    public void Cleanup_does_not_trim_whitespace_inside_a_raw_string_literal()
    {
        const string source = "class Sample\n{\n    string Text = \"\"\"\n        raw  \n        \"\"\";   \n}\n";

        var result = CSharpCleanupService.Clean(
            "Sample.cs", source,
            new CSharpCleanupOptions(OrganizeUsings: false));

        Assert.Null(result.Error);
        var updated = Assert.Single(Assert.Single(result.Edit!.Changes).Value).NewText;
        Assert.Contains("raw  \n", updated);
        Assert.Contains("\"\"\";\n", updated);
    }

    [Fact]
    public void Cleanup_reports_no_change_when_the_profile_is_already_clean()
    {
        const string source = "using System;\n\nclass Sample\n{\n}\n";

        var result = CSharpCleanupService.Clean(
            "Sample.cs", source,
            new CSharpCleanupOptions(OrganizeUsings: false));

        Assert.Null(result.Edit);
        Assert.Contains("変更はありません", result.Error);
    }

    [Fact]
    public void Cleanup_uses_the_Roslyn_CSharp_formatter_and_editorconfig_indent_size()
    {
        const string source = "class Sample{void Run(){int value=1;}}";

        var result = CSharpCleanupService.Clean(
            "Sample.cs", source,
            new CSharpCleanupOptions(
                OrganizeUsings: false,
                Format: true,
                InsertFinalNewline: true,
                IndentSize: 2,
                TabWidth: 2,
                UseTabs: false));

        Assert.Null(result.Error);
        var updated = Assert.Single(Assert.Single(result.Edit!.Changes).Value).NewText;
        Assert.Equal("class Sample\n{\n  void Run()\n  {\n    int value = 1;\n  }\n}\n", updated);
        Assert.Contains("C#コードを整形", result.Summary);
    }

    [Fact]
    public void Cleanup_skips_only_format_for_invalid_syntax_and_keeps_safe_layout_cleanup()
    {
        const string source = "class Broken {  \n";

        var result = CSharpCleanupService.Clean(
            "Broken.cs", source,
            new CSharpCleanupOptions(
                OrganizeUsings: false,
                Format: true,
                InsertFinalNewline: true));

        Assert.Null(result.Error);
        var updated = Assert.Single(Assert.Single(result.Edit!.Changes).Value).NewText;
        Assert.Equal("class Broken {\n", updated);
        Assert.DoesNotContain("C#コードを整形", result.Summary);
    }

    [Fact]
    public void Generated_workspace_edits_are_formatted_before_they_reach_the_host()
    {
        const string path = "C:\\work\\Generated.cs";
        const string source = "class Sample{void Run(){int value=1;}}";
        var uri = LspUri.FromPath(path);
        var edit = new LspWorkspaceEdit(
            new Dictionary<string, IReadOnlyList<LspTextEdit>>(StringComparer.OrdinalIgnoreCase)
            {
                [uri] = [new LspTextEdit(
                    new LspRange(new LspPosition(0, source.Length), new LspPosition(0, source.Length)),
                    "")],
            });

        var formatted = CSharpGeneratedEditFormatter.FormatCurrentFile(
            path, source, edit, new CSharpCleanupOptions(
                Format: true, IndentSize: 2, TabWidth: 2, UseTabs: false));

        var newText = Assert.Single(formatted.Changes[uri]).NewText;
        Assert.Equal("class Sample\n{\n  void Run()\n  {\n    int value = 1;\n  }\n}", newText);
    }

    [Fact]
    public void Generated_edit_formatting_preserves_raw_string_content()
    {
        const string path = "C:\\work\\Raw.cs";
        const string source = "class Sample{string Text=\"\"\"\n  raw  \n  \"\"\";}";
        var uri = LspUri.FromPath(path);
        var edit = new LspWorkspaceEdit(
            new Dictionary<string, IReadOnlyList<LspTextEdit>>(StringComparer.OrdinalIgnoreCase)
            {
                [uri] = [new LspTextEdit(
                    new LspRange(new LspPosition(0, source.Length), new LspPosition(0, source.Length)), "")],
            });

        var formatted = CSharpGeneratedEditFormatter.FormatCurrentFile(
            path, source, edit, new CSharpCleanupOptions(Format: true));

        var newText = Assert.Single(formatted.Changes[uri]).NewText;
        Assert.Contains("raw  \n", newText);
    }

    [Fact]
    public void Workspace_edit_formatting_also_formats_a_newly_created_document()
    {
        const string path = "C:\\work\\Extracted.cs";
        const string generated = "class Extracted{void Run(){int value=1;}}";
        var uri = LspUri.FromPath(path);
        var edit = new LspWorkspaceEdit(
            new Dictionary<string, IReadOnlyList<LspTextEdit>>(StringComparer.OrdinalIgnoreCase)
            {
                [uri] = [new LspTextEdit(
                    new LspRange(new LspPosition(0, 0), new LspPosition(0, 0)), generated)],
            },
            FileOperations: [new LspFileOperation(LspFileOperationKind.Create, uri)]);

        var formatted = CSharpGeneratedEditFormatter.FormatWorkspace(
            edit, new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) { [path] = "" },
            _ => new CSharpCleanupOptions(Format: true, IndentSize: 2, TabWidth: 2, UseTabs: false));

        Assert.Equal("class Extracted\n{\n  void Run()\n  {\n    int value = 1;\n  }\n}",
            Assert.Single(formatted.Changes[uri]).NewText);
        Assert.Single(formatted.FileOperations!);
    }

    [Fact]
    public void Semantic_operation_attaches_the_source_snapshot_to_its_edit()
    {
        const string path = "C:\\work\\GeneratedFromJson.cs";
        const string source = "class Container { }";
        var result = CSharpSemanticOperations.GenerateJsonTypes(
            null, path, source, 0, source.Length, "{\"id\":1}", "Payload");

        Assert.Null(result.Error);
        Assert.Equal(source, result.ExpectedTexts![path]);
    }

    [Fact]
    public void Edit_snapshot_validator_rejects_stale_text_and_allows_missing_new_files()
    {
        const string root = "C:\\work";
        const string path = "C:\\work\\Sample.cs";
        var expected = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            [path] = "class Sample { }",
        };

        Assert.Contains("本文が変更", CSharpEditSnapshotValidator.Validate(
            expected, [root], _ => "class Sample { int Value; }"));
        Assert.Null(CSharpEditSnapshotValidator.Validate(
            new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["C:\\work\\Created.cs"] = "",
            },
            [root], _ => null));
        Assert.Contains("ワークスペース外", CSharpEditSnapshotValidator.Validate(
            expected, ["C:\\other"], _ => expected[path]));
    }
}
