using System.IO;
using Editor.Core.Lsp;
using sk0ya.Loomo.CSharp.Configuration;
using sk0ya.Loomo.CSharp.Projects;

namespace sk0ya.Loomo.Tests;

/// <summary>「Using ディレクティブは必要ありません」に<b>なぜ</b>を添えられること。
/// 文面だけだと、使っている名前空間なのに不要と言われた＝誤検知に見える。</summary>
public sealed class CSharpDiagnosticExplanationServiceTests : IDisposable
{
    private readonly string _root = Path.Combine(Path.GetTempPath(),
        "LoomoDiagnosticExplanation_" + Guid.NewGuid().ToString("N"));

    public CSharpDiagnosticExplanationServiceTests() => Directory.CreateDirectory(_root);

    [Fact]
    public void Names_the_global_using_that_makes_the_directive_redundant()
    {
        var globals = Write("GlobalUsings.cs", """
            global using System;
            global using System.Windows;
            """);
        var path = Write("View.cs", "using System.Windows;\n\npublic class View { }\n");

        var explanation = Explain(path, Range(0, 0, 0, 21), globals, path);

        Assert.Equal("1行目は GlobalUsings.cs:2 の global using と重複しています（消しても解決は変わりません）。",
            explanation);
    }

    /// <summary>Roslyn が返す範囲は using の塊を<b>まとめて</b>指していて、その中の1本1本が
    /// 不要という意味ではない（実機では、まとめて指された範囲に本文で使っている using が入っていた）。
    /// だから重複だけを言い、残りが「使われていない」とは<b>言わない</b>——理由を足したつもりで
    /// 嘘を足さないため。範囲そのものは事実なので、何行目をまとめて指しているかは言う。</summary>
    [Fact]
    public void Says_only_what_it_verified_about_a_merged_range()
    {
        var globals = Write("GlobalUsings.cs", "global using System;\nglobal using System.Windows;\n");
        var path = Write("View.cs", """
            using System;
            using System.Windows;
            using System.Collections.ObjectModel;

            public class View { }
            """);

        var explanation = Explain(path, Range(0, 0, 2, 37), globals, path);

        Assert.Equal(
            "この指摘は 1〜3行目 の using 3 件をまとめて指しています。" +
            "うち 2 件は GlobalUsings.cs の global using と重複しています（消しても解決は変わりません）。",
            explanation);
    }

    /// <summary>全部が重複なら、そう言い切れる。</summary>
    [Fact]
    public void Says_all_when_every_directive_is_a_duplicate()
    {
        var globals = Write("GlobalUsings.cs", "global using System;\nglobal using System.Windows;\n");
        var path = Write("View.cs", "using System;\nusing System.Windows;\n");

        Assert.Equal(
            "この指摘は 1〜2行目 の using 2 件をまとめて指しています。" +
            "いずれも GlobalUsings.cs の global using と重複しています（消しても解決は変わりません）。",
            Explain(path, Range(0, 0, 1, 21), globals, path));
    }

    /// <summary>重複が1件も無ければ黙る。Roslyn の文面に足せることが無い。</summary>
    [Fact]
    public void Stays_silent_when_nothing_is_a_duplicate()
    {
        var path = Write("View.cs", "using System.Reflection;\nusing System.Text;\n");

        Assert.Null(Explain(path, Range(0, 0, 1, 18), path));
    }

    /// <summary>ImplicitUsings が生成した global using は中間出力の中にあり、開いても仕方がない。
    /// 「どこを見ればいいか」が違うので、そう言い分ける。</summary>
    [Fact]
    public void Calls_generated_global_usings_by_what_they_are()
    {
        var generated = Path.Combine(_root, "obj", "Debug", "Sample.GlobalUsings.g.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(generated)!);
        File.WriteAllText(generated, "// <auto-generated/>\nglobal using global::System.Linq;\n");
        var path = Write("View.cs", "using System.Linq;\n");

        var explanation = Explain(path, Range(0, 0, 0, 18), generated, path);

        Assert.NotNull(explanation);
        Assert.Contains("ImplicitUsings", explanation);
    }

    [Fact]
    public void Says_nothing_it_cannot_back_up()
    {
        var path = Write("View.cs", "using System.Linq;\n");

        // 説明を持っていない規則。
        Assert.Null(Explain(path, Range(0, 0, 0, 18), [path], "CS0103"));
        // using ではない範囲（行を切り直しても using が1本も無い）。
        Assert.Null(Explain(path, Range(2, 0, 2, 5), [path], "IDE0005"));
        // 規則名そのものが無い診断。
        Assert.Null(new CSharpDiagnosticExplanationService().Explain(
            null, path, "using System.Linq;\n",
            new LspDiagnostic(Range(0, 0, 0, 18), "…", DiagnosticSeverity.Hint)));
    }

    /// <summary>別名付き（<c>using A = B;</c>）は別物。global using と名前が重なっても重複ではない。</summary>
    [Fact]
    public void Aliases_are_not_duplicates()
    {
        var globals = Write("GlobalUsings.cs", "global using System.Windows;\n");
        var path = Write("View.cs", "using Win = System.Windows;\n");

        Assert.Null(Explain(path, Range(0, 0, 0, 27), globals, path));
    }

    private string? Explain(
        string filePath, LspRange range, params string[] compileFiles) =>
        Explain(filePath, range, compileFiles, "IDE0005");

    private string? Explain(string filePath, LspRange range, string[] compileFiles, string code)
    {
        var target = new TargetFrameworkModel("net10.0", [], "latest",
            [.. compileFiles.Select(file => new ProjectItem(Path.GetFileName(file), file))], [], [], []);
        var project = new ProjectModel("Sample", Path.Combine(_root, "Sample.csproj"), _root,
            [], [target], "net10.0", false, ProjectLoadState.Ready);
        var solution = new SolutionModel(null, "Sample", _root, [project], ProjectLoadState.Ready);

        return new CSharpDiagnosticExplanationService().Explain(
            solution, filePath, File.ReadAllText(filePath),
            new LspDiagnostic(range, "Using ディレクティブは必要ありません。",
                DiagnosticSeverity.Hint, "Roslyn", code));
    }

    private static LspRange Range(int startLine, int startColumn, int endLine, int endColumn) =>
        new(new LspPosition(startLine, startColumn), new LspPosition(endLine, endColumn));

    private string Write(string name, string content)
    {
        var path = Path.Combine(_root, name);
        File.WriteAllText(path, content);
        return path;
    }

    public void Dispose()
    {
        try { Directory.Delete(_root, recursive: true); } catch { }
    }
}
