using System.Text.RegularExpressions;
using Editor.Core.Lsp;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Formatting;
using Microsoft.CodeAnalysis.Host.Mef;
using Microsoft.CodeAnalysis.Options;
using Microsoft.CodeAnalysis.Text;

namespace sk0ya.Loomo.CSharp.Refactoring;

/// <summary>C# 固有の安全な cleanup profile。
///
/// <para>Roslyn の意味モデルを持たない状態で「未使用」を推測して削除すると、条件付きコンパイルや
/// global using を壊す。そのためここでは、確実に意味を変えない using の整理、行末空白、改行、末尾改行だけを
/// 扱う。未使用 using の判定は Roslyn analyzer／LSP に任せる。</para>
/// <para>生成コードは既定で除外する。プレビューはホスト側の通常の WorkspaceEdit 経路が担当する。</para>
/// </summary>
public static class CSharpCleanupService
{
    private static readonly Regex GeneratedMarker = new(
        @"(?im)^\s*(?://|/\*|\*)\s*<auto-generated\b",
        RegexOptions.CultureInvariant | RegexOptions.Compiled);

    public static CSharpCleanupResult Clean(
        string filePath,
        string sourceText,
        CSharpCleanupOptions? options = null)
        => CleanCore(filePath, sourceText, options, semanticCompilation: null);

    /// <summary>意味解析付きcleanupの内部経路。Roslyn型をAppへ公開しない。</summary>
    internal static CSharpCleanupResult Clean(
        string filePath,
        string sourceText,
        CSharpCleanupOptions? options,
        CSharpCompilation? semanticCompilation)
        => CleanCore(filePath, sourceText, options, semanticCompilation);

    private static CSharpCleanupResult CleanCore(
        string filePath,
        string sourceText,
        CSharpCleanupOptions? options,
        CSharpCompilation? semanticCompilation)
    {
        options ??= CSharpCleanupOptions.Default;
        if (!string.Equals(Path.GetExtension(filePath), ".cs", StringComparison.OrdinalIgnoreCase))
            return Failed("C# ファイルでのみcleanupを実行できます。");

        if (options.ExcludeGeneratedCode && GeneratedMarker.IsMatch(sourceText))
            return new CSharpCleanupResult(null, "生成コードのためcleanupから除外しました。", null, 0, true);

        var original = SourceText.From(sourceText);
        var current = original;
        var notes = new List<string>();

        if (options.OrganizeUsings)
        {
            var usingResult = CSharpUsingOrganizer.Organize(
                filePath, current.ToString(), options.SortSystemDirectivesFirst,
                options.RemoveUnusedUsings ? semanticCompilation : null);
            if (usingResult.Edit is { } usingEdit)
            {
                current = ApplyLspEdits(current, usingEdit.Changes.Values.SelectMany(x => x));
                notes.Add(usingResult.Summary);
            }
            else if (usingResult.Error is { } usingError &&
                     !usingError.Contains("既に整理", StringComparison.Ordinal))
            {
                // コメント付きusingは移動せず、他の安全なcleanupだけ続行する。
                notes.Add($"using整理はスキップ（{usingError}）");
            }
        }

        // 未使用usingのCS8019位置はCompilation作成時の本文に対して有効なので、
        // semantic cleanupを先に行い、その後にRoslyn formatterでレイアウトを整える。
        if (options.Format)
        {
            var before = current;
            current = FormatCSharp(current, options);
            if (!before.ContentEquals(current)) notes.Add("C#コードを整形");
        }

        if (options.TrimTrailingWhitespace)
        {
            var before = current;
            current = TrimTrailingWhitespace(current);
            if (!before.ContentEquals(current)) notes.Add("行末空白を削除");
        }

        if (options.EndOfLine is { Length: > 0 } endOfLine)
        {
            var before = current;
            current = NormalizeLineEndings(current, endOfLine);
            if (!before.ContentEquals(current)) notes.Add($"改行コードを{endOfLine}へ統一");
        }

        if (options.InsertFinalNewline is { } insertFinalNewline)
        {
            var before = current;
            current = NormalizeFinalNewline(current, insertFinalNewline, options.EndOfLine);
            if (!before.ContentEquals(current))
                notes.Add(insertFinalNewline ? "ファイル末尾に改行を追加" : "末尾の余分な改行を削除");
        }

        if (original.ContentEquals(current))
            return Failed("cleanup対象の変更はありません。");

        var uri = LspUri.FromPath(Path.GetFullPath(filePath));
        var edit = new LspWorkspaceEdit(
            new Dictionary<string, IReadOnlyList<LspTextEdit>>(StringComparer.OrdinalIgnoreCase)
            {
                [uri] = [new LspTextEdit(ToRange(original), current.ToString())],
            });
        var changedLines = CountChangedLines(original.ToString(), current.ToString());
        var detail = notes.Count == 0 ? "C# cleanup" : string.Join("、", notes);
        return new CSharpCleanupResult(
            edit, $"{detail}（{changedLines}行変更）", null, changedLines, false);
    }

    private static SourceText ApplyLspEdits(SourceText source, IEnumerable<LspTextEdit> edits)
    {
        var changes = edits.Select(edit => new TextChange(
                ToTextSpan(source, edit.Range), edit.NewText))
            .OrderByDescending(change => change.Span.Start)
            .ToArray();
        return changes.Length == 0 ? source : source.WithChanges(changes);
    }

    private static SourceText TrimTrailingWhitespace(SourceText source)
    {
        var stringSpans = CSharpSyntaxTree.ParseText(source).GetRoot().DescendantTokens()
            .Where(token => token.IsKind(SyntaxKind.StringLiteralToken) ||
                            token.Kind().ToString().Contains("StringLiteral", StringComparison.Ordinal) ||
                            token.Kind().ToString().Contains("InterpolatedString", StringComparison.Ordinal))
            .Select(token => token.Span)
            .ToArray();
        var changes = new List<TextChange>();
        foreach (var line in source.Lines)
        {
            var start = line.End;
            while (start > line.Start && (source[start - 1] == ' ' || source[start - 1] == '\t')) start--;
            if (start == line.End || stringSpans.Any(span => span.Start < line.End && span.End > start)) continue;
            changes.Add(new TextChange(TextSpan.FromBounds(start, line.End), ""));
        }
        return changes.Count == 0 ? source : source.WithChanges(changes);
    }

    private static SourceText NormalizeLineEndings(SourceText source, string requested)
    {
        var newline = requested.Trim().ToLowerInvariant() switch
        {
            "crlf" => "\r\n",
            "cr" => "\r",
            _ => "\n",
        };
        var stringSpans = CSharpSyntaxTree.ParseText(source).GetRoot().DescendantTokens()
            .Where(token => token.Kind().ToString().Contains("StringLiteral", StringComparison.Ordinal) ||
                            token.Kind().ToString().Contains("InterpolatedString", StringComparison.Ordinal))
            .Select(token => token.Span)
            .ToArray();
        var changes = new List<TextChange>();
        foreach (var line in source.Lines)
        {
            var span = TextSpan.FromBounds(line.End, line.EndIncludingLineBreak);
            if (span.Length == 0 || stringSpans.Any(token => token.Start < span.End && token.End > span.Start)) continue;
            if (!string.Equals(source.ToString(span), newline, StringComparison.Ordinal))
                changes.Add(new TextChange(span, newline));
        }
        return changes.Count == 0 ? source : source.WithChanges(changes);
    }

    private static SourceText NormalizeFinalNewline(
        SourceText source, bool insert, string? requestedEndOfLine)
    {
        var text = source.ToString();
        var newline = requestedEndOfLine?.Trim().ToLowerInvariant() switch
        {
            "crlf" => "\r\n",
            "cr" => "\r",
            _ => "\n",
        };
        var withoutFinalNewlines = text.TrimEnd('\r', '\n');
        var result = insert ? withoutFinalNewlines + newline : withoutFinalNewlines;
        return string.Equals(text, result, StringComparison.Ordinal) ? source : SourceText.From(result);
    }

    /// <summary>RoslynのC# formatterをcleanup profileへ接続する。構文エラーがある本文は、formatterが
    /// 部分的に書き換えて壊す可能性があるため、formatだけをスキップして安全なレイアウト処理は続ける。</summary>
    private static SourceText FormatCSharp(SourceText source, CSharpCleanupOptions options)
    {
        var root = CSharpSyntaxTree.ParseText(source).GetRoot();
        if (root.GetDiagnostics().Any(diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error))
            return source;

        try
        {
            using var workspace = new AdhocWorkspace(MefHostServices.Create(
                MefHostServices.DefaultAssemblies.Concat([
                    typeof(Microsoft.CodeAnalysis.CSharp.Formatting.CSharpFormattingOptions).Assembly])));
            var formatOptions = workspace.Options;
            if (options.IndentSize is { } indentSize)
                formatOptions = formatOptions.WithChangedOption(
                    FormattingOptions.IndentationSize, LanguageNames.CSharp, indentSize);
            if (options.TabWidth is { } tabWidth)
                formatOptions = formatOptions.WithChangedOption(
                    FormattingOptions.TabSize, LanguageNames.CSharp, tabWidth);
            if (options.UseTabs is { } useTabs)
                formatOptions = formatOptions.WithChangedOption(
                    FormattingOptions.UseTabs, LanguageNames.CSharp, useTabs);
            // Formatterは既存の改行を尊重して、1行に詰まった本文へ改行を新設しないことがある。
            // NormalizeWhitespaceで構造上の改行を先に作り、その後Formatterへeditorconfigの幅を渡す。
            var indentation = options.UseTabs == true
                ? "\t"
                : new string(' ', options.IndentSize ?? 4);
            var normalized = root.NormalizeWhitespace(indentation, "\n");
            var formatted = Formatter.Format(normalized, workspace, formatOptions);
            return formatted.ToFullString() is { } text && text.Length > 0
                ? SourceText.From(text)
                : source;
        }
        catch (ArgumentException)
        {
            return source;
        }
        catch (InvalidOperationException)
        {
            return source;
        }
    }

    private static TextSpan ToTextSpan(SourceText source, LspRange range)
        => TextSpan.FromBounds(
            source.Lines.GetPosition(new LinePosition(range.Start.Line, range.Start.Character)),
            source.Lines.GetPosition(new LinePosition(range.End.Line, range.End.Character)));

    private static LspRange ToRange(SourceText source)
    {
        var end = source.Lines.GetLinePosition(source.Length);
        return new LspRange(new LspPosition(0, 0), new LspPosition(end.Line, end.Character));
    }

    private static int CountChangedLines(string original, string updated)
    {
        var before = original.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var after = updated.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n');
        var count = 0;
        for (var i = 0; i < Math.Max(before.Length, after.Length); i++)
            if (i >= before.Length || i >= after.Length || !string.Equals(before[i], after[i], StringComparison.Ordinal)) count++;
        return count;
    }

    private static CSharpCleanupResult Failed(string error) => new(null, "", error, 0, false);
}

public sealed record CSharpCleanupOptions(
    bool OrganizeUsings = true,
    bool TrimTrailingWhitespace = true,
    bool Format = false,
    string? EndOfLine = null,
    bool? InsertFinalNewline = true,
    bool ExcludeGeneratedCode = true,
    bool SortSystemDirectivesFirst = true,
    int? IndentSize = null,
    int? TabWidth = null,
    bool? UseTabs = null,
    bool RemoveUnusedUsings = false)
{
    public static CSharpCleanupOptions Default { get; } = new();
}

public sealed record CSharpCleanupResult(
    LspWorkspaceEdit? Edit,
    string Summary,
    string? Error = null,
    int ChangedLines = 0,
    bool IsGeneratedCode = false,
    IReadOnlyDictionary<string, string>? ExpectedTexts = null);
